backend:
  name: github
  repo: dangoslen/dangoslen-me-site

media_folder: static/assets
public_folder: public/assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: tr
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
